image: "python:3"

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - pip3 install cython
  script:
    - make clean
    - make debian arch=arm64
  artifacts:
    paths:
      - build/jxserving*
    expire_in: 1 day
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/

deploy:
  stage: deploy
  environment:
    name: package
    url: https://packages.debian.jiangxingai.com
  script:
    - make push_to_source
    
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/
